version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - ${PWD}/data/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    volumes:
    - ${PWD}/data/postgresql:/var/lib/postgresql:Z

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.16.6
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - GITLAB_HOST=
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=/gitlab/
    - GITLAB_SECRETS_DB_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_SECRET_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_OTP_KEY_BASE=qcs-gitlab-app

    - GITLAB_ROOT_EMAIL=
    - GITLAB_ROOT_PASSWORD=

    - SMTP_ENABLED=false
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=
    - SMTP_PASS=
    - SMTP_TLS=false
    volumes:
    - ${PWD}/data/gitlab:/home/git/data:Z
